version: "3.9"
services:
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root2
      ME_CONFIG_MONGODB_ADMINPASSWORD: root2
