version: "3.9"
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root2
      MONGO_INITDB_ROOT_PASSWORD: root2
      MONGO_INITDB_DATABASE: my-db2
    volumes:
      - 'dbdata:/data/db'
volumes:
  dbdata:
